import type { Metadata } from "next";
export const metadata: Metadata = { title: "Conditions générales de vente", description: "Informations sur les ventes et paiements associés au BDE CERI.", alternates: { canonical: "/cgv" } };

export default function TermsOfSale() {
  return <article className="mx-auto max-w-4xl px-6 py-20 text-on-surface">
    <p className="mb-3 text-sm font-bold uppercase tracking-widest text-tertiary">BDE CERI · boutique</p>
    <h1 className="mb-8 font-headline text-4xl font-bold">Conditions générales de vente</h1>
    <div className="space-y-8 leading-relaxed text-on-surface-variant">
      <section><h2 className="mb-2 text-xl font-bold text-on-surface">1. Vendeur et périmètre</h2><p>Le vendeur est <strong>[nom officiel de l’association à compléter]</strong>, siège : <strong>[adresse à compléter]</strong>, RNA/SIREN : <strong>[numéros à compléter]</strong>, contact : <a className="underline" href="mailto:lebdeceri@gmail.com">lebdeceri@gmail.com</a>. Les produits affichés sur le site sont commandés et payés sur la boutique HelloAsso du BDE CERI. Avant toute commande, l’offre, son prix, les modalités de retrait ou de livraison et les conditions applicables doivent être consultés sur la page de paiement HelloAsso.</p></section>
      <section><h2 className="mb-2 text-xl font-bold text-on-surface">2. Formation de la commande et paiement</h2><p>Le site du BDE ne recueille pas directement les coordonnées de paiement et ne confirme pas à lui seul une commande. La commande est passée lorsque l’utilisateur la valide sur HelloAsso, selon le parcours et les conditions présentés par ce service. Les moyens de paiement, frais éventuels, confirmation et justificatifs sont indiqués au moment de l’achat.</p></section>
      <section><h2 className="mb-2 text-xl font-bold text-on-surface">3. Disponibilité, retrait et livraison</h2><p>Les disponibilités et délais dépendent de l’offre publiée pour chaque article. Les informations affichées au moment de la commande sur HelloAsso font foi. En cas de question sur une commande ou son retrait, contacter le BDE avec les références transmises lors de l’achat.</p></section>
      <section><h2 className="mb-2 text-xl font-bold text-on-surface">4. Rétractation, annulation et réclamation</h2><p>Les droits applicables dépendent notamment de la nature du produit, de l’acheteur et de la transaction. Les conditions de rétractation, d’annulation, de remboursement et de réclamation doivent être précisées dans l’offre HelloAsso et confirmées par l’association avant ouverture de la vente. Pour toute demande, écrire à <a className="underline" href="mailto:lebdeceri@gmail.com">lebdeceri@gmail.com</a>.</p></section>
      <section><h2 className="mb-2 text-xl font-bold text-on-surface">5. Dons</h2><p>Un don à l’association est facultatif, distinct d’un achat et ne conditionne ni l’accès au site ni le refus des brookies. Le montant, le bénéficiaire, le reçu éventuel et les modalités sont présentés par HelloAsso avant validation. Aucun avantage fiscal n’est garanti par le présent site.</p></section>
      <section><h2 className="mb-2 text-xl font-bold text-on-surface">6. Médiation et droit applicable</h2><p>Les coordonnées du médiateur de la consommation compétent seront ajoutées si cette obligation s’applique à la vente proposée. Les présentes conditions sont soumises au droit français, sous réserve des règles impératives applicables au consommateur.</p></section>
      <p className="rounded-xl border border-tertiary/20 bg-tertiary/5 p-4 text-sm">Cette page doit être complétée et vérifiée pour chaque type d’offre avant la mise en vente : vendeur légal, prix, retrait/livraison, rétractation et médiateur le cas échéant.</p>
    </div>
  </article>;
}
