import type { Metadata } from "next";
export const metadata: Metadata = { title: "Politique de confidentialité", description: "Comment le BDE CERI traite les données personnelles sur son site.", alternates: { canonical: "/confidentialite" } };

export default function PrivacyPolicy() {
  return <article className="mx-auto max-w-4xl px-6 py-20 text-on-surface">
    <p className="mb-3 text-sm font-bold uppercase tracking-widest text-tertiary">BDE CERI · données personnelles</p>
    <h1 className="mb-8 font-headline text-4xl font-bold">Politique de confidentialité</h1>
    <div className="space-y-8 leading-relaxed text-on-surface-variant">
      <section><h2 className="mb-2 text-xl font-bold text-on-surface">Responsable du traitement</h2><p>Le responsable est <strong>[nom officiel de l’association à compléter]</strong>, siège : <strong>[adresse à compléter]</strong>. Pour toute demande : <a className="underline" href="mailto:lebdeceri@gmail.com">lebdeceri@gmail.com</a>. Délégué à la protection des données : <strong>[coordonnées à compléter si un DPO est désigné]</strong>.</p></section>
      <section><h2 className="mb-2 text-xl font-bold text-on-surface">Données et finalités</h2><p>Lorsque vous choisissez « Accepter les statistiques », le site utilise les en-têtes de connexion pour produire une empreinte HMAC de l’adresse IP combinée à la date du jour dans le fuseau Europe/Paris, ainsi qu’une catégorie d’appareil (mobile, tablette ou ordinateur) déduite du navigateur. L’adresse IP brute et la chaîne complète du navigateur ne sont pas conservées dans la base de statistiques. Ces données servent à dédupliquer les visites par adresse IP publique et par jour dans le fuseau Europe/Paris, estimer les visiteurs actifs à partir d’un signal reçu dans les cinq dernières minutes, et produire des statistiques cumulées par appareil. Plusieurs personnes partageant la même adresse IP publique peuvent être regroupées ; une même personne utilisant des adresses IP différentes peut être comptée plusieurs fois. Le total additionne les visites uniques quotidiennes, pas des personnes identifiées de manière permanente.</p><p className="mt-2">La base légale est votre consentement. Les visites des personnes qui refusent ou ne choisissent pas sont exclues des statistiques. Le brookie nécessaire mémorise votre choix pendant six mois. Vous pouvez le modifier depuis le lien « Gérer les brookies » en bas de page.</p></section>
      <section><h2 className="mb-2 text-xl font-bold text-on-surface">Conservation et destinataires</h2><p>Les empreintes quotidiennes sont supprimées automatiquement à la première visite consentie enregistrée pour un nouveau jour. Les compteurs agrégés (sans empreinte individuelle) sont conservés pour suivre le total depuis le lancement du dispositif. Les statistiques sont hébergées dans le projet Supabase utilisé par l’association ; les informations sur la région d’hébergement et les sous-traitants doivent être vérifiées par le BDE et précisées ici avant publication définitive.</p></section>
      <section><h2 className="mb-2 text-xl font-bold text-on-surface">Vos droits</h2><p>Vous pouvez retirer votre consentement à tout moment en changeant votre préférence. Vous pouvez également demander l’accès, la rectification, l’effacement, la limitation ou vous opposer aux traitements lorsque ces droits sont applicables, en écrivant au contact ci-dessus. Vous pouvez adresser une réclamation à la CNIL. Un retrait empêche les futurs comptages ; les compteurs déjà agrégés ne permettent pas d’isoler une visite individuelle.</p></section>
      <section><h2 className="mb-2 text-xl font-bold text-on-surface">Services externes et transferts</h2><p>Le paiement et la boutique peuvent être fournis sur HelloAsso, avec leurs propres traitements et conditions. Les pages externes ne sont pas contrôlées par le BDE. Le BDE doit compléter les informations sur l’hébergement et les transferts internationaux liés aux services configurés (dont Supabase et HelloAsso) avant publication définitive.</p></section>
      <section><h2 className="mb-2 text-xl font-bold text-on-surface">Contact et mise à jour</h2><p>Pour toute question sur les données, contactez <a className="underline" href="mailto:lebdeceri@gmail.com">lebdeceri@gmail.com</a>. Dernière mise à jour : 8 octobre 2026.</p></section>
    </div>
  </article>;
}
